### ISSUE TITLE
Create an .mdb (microsoft access database) files merging function for merging different .mdb files into one.

### ISSUE THREAD

**Issue by DemevengDerrick** [WorldHealthOrganization/poliprep#14]
AFP surveillance, AFP Lab and ES databses are shared on a weekly basis to the regional office for merging. We have 17 mdb files for ES, 17 for AFP Lab and 3 AFP Surveillance. This function will help automate this process by abstracting the bulk work.

```[tasklist]
### Tasks
- [x] Define the function framework
- [x] Write the code
- [x] Write test for the function
- [x] Document the code
- [x] Submit to the dev for review
```

**Comment by DemevengDerrick** [comment]
Done
